music/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    # url(r'^music/(?P<id>\d+)/$', views.artists, name='detail'),
]

music_library/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^music/', include("music.urls", namespace="music")),

]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse



class Artist (models.Model):
    #artist name
    name = models.CharField(max_length = 40)
    
    #link to artist wiki
    wiki_url = models.URLField(max_length=200, blank=True)
    
    #is artist solo or with a group
    SOLO = "Solo Artist"
    BAND = "Band"
    
    SOLO_VS_BAND_CHOICES = (
        (SOLO, "Solo Artist"),
        (BAND, "Band"),
    )
    solo_vs_band = models.CharField(max_length = 40, 
        choices = SOLO_VS_BAND_CHOICES, 
        default = SOLO,
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse ("artists:detail", kwargs={"id":self.pk})


class Album (models.Model):
    #album name
    name = models.CharField(max_length = 100)

    #what format is the album?
    VINYL = "Vinyl"
    CD = "Compact Disc"
    DIGITAL = "Digital"
    PHONOGRAPH = "Phonograph Cylinder"
    CASSETTE = "Compact Cassette"
    
    AUDIO_FORMAT = (
    (VINYL, "Vinyl"),
    (CD, "Compact Disc"),
    (DIGITAL, "Digital"),
    (PHONOGRAPH, "Phonograph Cylinder"),        
    )
    audio_format = models.CharField(max_length = 40,
        choices = AUDIO_FORMAT,
        default = DIGITAL,
    )

    #what year was the album released
    year = models.IntegerField ()

    #what genre
    ROCK = "Rock 'n Roll"
    PUNK = "Punk"

    GENRE = (
        (ROCK, "Rock 'n Roll"),
        (PUNK, "Punk"),
    )
    genre = models.CharField (max_length = 40, 
        choices = GENRE,
        default = ROCK)

    #is the album a collection?
    collection = models.BooleanField (default = False)

    #album art
    # cover_art = models.ImageField ()

    #link between Album and Artist models/classes
    artists = models.ManyToManyField("Artist")

    #do I own this album?
    owned = models.BooleanField(default = False)

    def __str__(self):
        return self.name



class Song (models.Model):
    #song name
    name = models.CharField(max_length = 100)

    #track number
    track_number = models.IntegerField()

    #track length
    track_length = models.CharField(max_length = 20)

    #link from Song to Album models/classes
    album = models.ForeignKey("Album")

    def __str__(self):
        return self.name



class Composer (models.Model):
    #track composer
    name = models.CharField(max_length = 40)

    #link between Composer and Song models/classes
    songs = models.ManyToManyField("Song")

    def __str__(self):
        return self.name

music/views.py
from django.shortcuts import render, get_object_or_404

from .models import Artist

def index(request):

    # artists = Artist.objects.all()

    context = {
        # "artists" = artists
    }

    return render (request, "music/index.html", context)


# def Artists (request, id):
#     artists = get_object_or_404(Artist, pk=id)

#     context = {
#         "artists":artists
#     }

#     return render (request, "music/artist.html", context)

music/templates/music/artist.html
{% extends "music/base.html" %}

{% block title %}
    {{ block.super }}
    - Artist
{% endblock title %}

{% block content %}

    <h2>
        {{ artists.name }}
    </h2>

{% endblock content %}

music/templates/music/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}
            Music
        {% endblock title %}
    </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'music/styles.css' %}" />
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
                <a href="{% url 'music:index' %}" class="navbar-brand">
                    Music
                </a>
            </div>
          </div>
        </nav>
    </header>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    <footer class="page-footer">
        <hr>
        <div class="container">
            &copy; Awesome Inc U. Bootcamp 2016
        </div>
    </footer>

    <script   src="https://code.jquery.com/jquery-3.1.0.min.js"   integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="   crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

music/templates/music/index.html
{% extends "music/base.html" %}

{% block title %}
    {{ block.super }}
    - Index
{% endblock title %}

    

{% block content %}

        {% for artist in artists %}
            <li class="list-group-item">
                    <a href="{{artist.get_absolute_url}}">
                        {{artist.name}}               
                    </a>
            </li>
        {% endfor %}


{% endblock content %}